version: '3.3'

services:

  moseco:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python main.py
    container_name: 'moseco'
    env_file:
      - ./.env
